// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("MatDataProvider")>]
[<assembly: AssemblyProductAttribute("MatDataProvider")>]
[<assembly: AssemblyDescriptionAttribute("Type provider for .mat files")>]
[<assembly: AssemblyVersionAttribute("0.0.1")>]
[<assembly: AssemblyFileVersionAttribute("0.0.1")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "MatDataProvider"
    let [<Literal>] AssemblyProduct = "MatDataProvider"
    let [<Literal>] AssemblyDescription = "Type provider for .mat files"
    let [<Literal>] AssemblyVersion = "0.0.1"
    let [<Literal>] AssemblyFileVersion = "0.0.1"
